# http and https need separate rules if you don't force_ssl!
http://jsdevelopment.tech/* https://jsdevelopment.io/:splat 301!
https://jsdevelopment.tech/* https://jsdevelopment.io/:splat 301!

http://www.jsdevelopment.tech/* https://www.jsdevelopment.io/:splat 301!
https://www.jsdevelopment.tech/* https://www.jsdevelopment.io/:splat 301!
