[[redirects]]
  from = "*://jsdevelopment.tech"
  to = "*://jsdevelopment.io"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
